# Generated by Django 5.1.4 on 2024-12-15 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('aforo', models.BigIntegerField()),
            ],
            options={
                'db_table': 'EVENTO',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('area', models.TextField(blank=True, null=True)),
                ('presupuesto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MUNICIPIO',
            },
        ),
        migrations.CreateModel(
            name='MunicipioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.evento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.municipio')),
            ],
            options={
                'db_table': 'MUNICIPIO_has_EVENTO',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('edad', models.BigIntegerField()),
                ('sexo', models.CharField(blank=True, max_length=45, null=True)),
                ('ahorros', models.BigIntegerField(blank=True, null=True)),
                ('persona_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.persona')),
            ],
            options={
                'db_table': 'PERSONA',
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.persona'),
        ),
        migrations.CreateModel(
            name='PersonaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.evento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.persona')),
            ],
            options={
                'db_table': 'PERSONA_goes_EVENTO',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=500)),
                ('presupuesto', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.municipio')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.persona')),
            ],
            options={
                'db_table': 'PROYECTO',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=45)),
                ('capacidad', models.BigIntegerField()),
                ('niveles', models.BigIntegerField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.municipio')),
            ],
            options={
                'db_table': 'VIVIENDA',
            },
        ),
        migrations.CreateModel(
            name='PersonaVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.persona')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.vivienda', unique=True)),
            ],
            options={
                'db_table': 'PERSONA_has_VIVIENDA',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.vivienda'),
        ),
    ]
