# Generated by Django 5.1.4 on 2024-12-15 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='vivienda',
        ),
        migrations.AddField(
            model_name='persona',
            name='vivienda_residencial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residente', to='universo.vivienda'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viviendas_propiedad', to='universo.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='persona_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universo.persona'),
        ),
        migrations.DeleteModel(
            name='PersonaVivienda',
        ),
    ]
