# Generated by Django 5.1.4 on 2024-12-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0002_remove_persona_vivienda_persona_vivienda_residencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.BigIntegerField(),
        ),
    ]
