# Generated by Django 5.1.4 on 2024-12-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0003_alter_proyecto_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ahorros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
