# Generated by Django 5.1.4 on 2024-12-15 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0005_alter_persona_vivienda_residencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='vivienda_residencial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universo.vivienda'),
        ),
    ]
