# Generated by Django 5.1.4 on 2024-12-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0006_alter_persona_vivienda_residencial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='persona_relacionada',
            new_name='cabeza_de_familia',
        ),
    ]
