# Generated by Django 5.1.4 on 2024-12-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0007_rename_persona_relacionada_persona_cabeza_de_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no responder')], max_length=1),
        ),
    ]
