# Generated by Django 5.1.4 on 2024-12-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0011_alter_persona_ahorros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro'), ('N', 'Prefiero no responder')], max_length=1),
        ),
    ]
