# Generated by Django 5.1.4 on 2024-12-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0012_alter_persona_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='niveles',
            field=models.BigIntegerField(),
        ),
    ]
