# Generated by Django 5.1.4 on 2024-12-17 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0013_alter_vivienda_area_alter_vivienda_niveles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universo.persona'),
        ),
    ]
