# Generated by Django 5.1.4 on 2024-12-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0015_alter_vivienda_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='presupuesto',
            field=models.TextField(),
        ),
    ]
