# Generated by Django 5.1.4 on 2024-12-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0016_alter_municipio_area_alter_municipio_presupuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='persona',
            new_name='responsable',
        ),
        migrations.AlterField(
            model_name='municipio',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.TextField(choices=[('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
    ]
