# Generated by Django 5.1.4 on 2024-12-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0018_alter_proyecto_estado_alter_proyecto_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.persona'),
        ),
        migrations.AlterField(
            model_name='municipioevento',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.evento'),
        ),
        migrations.AlterField(
            model_name='municipioevento',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.municipio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cabeza_de_familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='vivienda_residencial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.vivienda'),
        ),
        migrations.AlterField(
            model_name='personaevento',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.evento'),
        ),
        migrations.AlterField(
            model_name='personaevento',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.persona'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.municipio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.persona'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.municipio'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.persona'),
        ),
    ]
