# Generated by Django 5.1.4 on 2024-12-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0019_alter_municipio_persona_alter_municipioevento_evento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonaEvento',
        ),
    ]
